/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class projekat_SysClass */

#ifndef _Included_projekat_SysClass
#define _Included_projekat_SysClass
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     projekat_SysClass
	 * Method:    generateFilter
	 * Signature: (JLjava/lang/String;Ljava/lang/Integer;Ljava/lang/String;Ljava/lang/String;)J
	 */
	JNIEXPORT jlong JNICALL Java_projekat_SysClass_generateFilter
	(JNIEnv*, jclass, jlong, jstring, jobject, jstring, jstring);

	/*
	 * Class:     projekat_SysClass
	 * Method:    _numberOfParticipantsGroupedByCountry
	 * Signature: (JJ)Ljava/util/HashMap;
	 */
	JNIEXPORT jobject JNICALL Java_projekat_SysClass__1numberOfParticipantsGroupedByCountry
	(JNIEnv*, jclass, jlong, jlong);

	/*
	 * Class:     projekat_SysClass
	 * Method:    _numberOfDisciplinesGroupedByOlGames
	 * Signature: (JJ)Ljava/util/HashMap;
	 */
	JNIEXPORT jobject JNICALL Java_projekat_SysClass__1numberOfDisciplinesGroupedByOlGames
	(JNIEnv*, jclass, jlong, jlong);

	/*
	 * Class:     projekat_SysClass
	 * Method:    _averageHeightGroupedByOlGames
	 * Signature: (JJ)Ljava/util/HashMap;
	 */
	JNIEXPORT jobject JNICALL Java_projekat_SysClass__1averageHeightGroupedByOlGames
	(JNIEnv*, jclass, jlong, jlong);

	/*
	 * Class:     projekat_SysClass
	 * Method:    _averageWeightGroupedByOlGames
	 * Signature: (JJ)Ljava/util/HashMap;
	 */
	JNIEXPORT jobject JNICALL Java_projekat_SysClass__1averageWeightGroupedByOlGames
	(JNIEnv*, jclass, jlong, jlong);

	/*
	 * Class:     projekat_SysClass
	 * Method:    _createObject
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_projekat_SysClass__1createObject
	(JNIEnv*, jclass);

	/*
	 * Class:     projekat_SysClass
	 * Method:    _deleteObject
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_projekat_SysClass__1deleteObject
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     projekat_SysClass
	 * Method:    _loadGroupMode
	 * Signature: (JLjava/lang/String;)Z
	 */
	JNIEXPORT jboolean JNICALL Java_projekat_SysClass__1loadGroupMode
	(JNIEnv*, jclass, jlong, jstring);

	/*
	 * Class:     projekat_SysClass
	 * Method:    _loadIndividualMode
	 * Signature: (JLjava/lang/String;I)Z
	 */
	JNIEXPORT jboolean JNICALL Java_projekat_SysClass__1loadIndividualMode
	(JNIEnv*, jclass, jlong, jstring, jint);

	/*
	 * Class:     projekat_SysClass
	 * Method:    _loadAthletes
	 * Signature: (JLjava/lang/String;)Z
	 */
	JNIEXPORT jboolean JNICALL Java_projekat_SysClass__1loadAthletes
	(JNIEnv*, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
